In [3]:
import pandas as pd
import numpy as np

In [4]:
fake=pd.read_csv('/content/Fake.csv.zip')

In [5]:
true=pd.read_csv('/content/True.csv.zip')

In [6]:
true.head()

,title,text,subject,date
0,"As U.S. budget fight looms, Republicans flip t...",WASHINGTON (Reuters) - The head of a conservat...,politicsNews,"December 31, 2017"
1,U.S. military to accept transgender recruits o...,WASHINGTON (Reuters) - Transgender people will...,politicsNews,"December 29, 2017"
2,Senior U.S. Republican senator: 'Let Mr. Muell...,WASHINGTON (Reuters) - The special counsel inv...,politicsNews,"December 31, 2017"
3,FBI Russia probe helped by Australian diplomat...,WASHINGTON (Reuters) - Trump campaign adviser ...,politicsNews,"December 30, 2017"
4,Trump wants Postal Service to charge 'much mor...,SEATTLE/WASHINGTON (Reuters) - President Donal...,politicsNews,"December 29, 2017"

In [7]:
fake.head()

,title,text,subject,date
0,Donald Trump Sends Out Embarrassing New Year’...,Donald Trump just couldn t wish all Americans ...,News,"December 31, 2017"
1,Drunk Bragging Trump Staffer Started Russian ...,House Intelligence Committee Chairman Devin Nu...,News,"December 31, 2017"
2,Sheriff David Clarke Becomes An Internet Joke...,"On Friday, it was revealed that former Milwauk...",News,"December 30, 2017"
3,Trump Is So Obsessed He Even Has Obama’s Name...,"On Christmas day, Donald Trump announced that ...",News,"December 29, 2017"
4,Pope Francis Just Called Out Donald Trump Dur...,Pope Francis used his annual Christmas Day mes...,News,"December 25, 2017"

In [8]:
true['label']=1

In [9]:
fake['label']=0;

In [10]:
news=pd.concat([fake,true],axis=0)

In [11]:
news.tail()

,title,text,subject,date,label
21412,'Fully committed' NATO backs new U.S. approach...,BRUSSELS (Reuters) - NATO allies on Tuesday we...,worldnews,"August 22, 2017",1
21413,LexisNexis withdrew two products from Chinese ...,"LONDON (Reuters) - LexisNexis, a provider of l...",worldnews,"August 22, 2017",1
21414,Minsk cultural hub becomes haven from authorities,MINSK (Reuters) - In the shadow of disused Sov...,worldnews,"August 22, 2017",1
21415,Vatican upbeat on possibility of Pope Francis ...,MOSCOW (Reuters) - Vatican Secretary of State ...,worldnews,"August 22, 2017",1
21416,Indonesia to buy $1.14 billion worth of Russia...,JAKARTA (Reuters) - Indonesia will buy 11 Sukh...,worldnews,"August 22, 2017",1

In [12]:
news

,title,text,subject,date,label
0,Donald Trump Sends Out Embarrassing New Year’...,Donald Trump just couldn t wish all Americans ...,News,"December 31, 2017",0
1,Drunk Bragging Trump Staffer Started Russian ...,House Intelligence Committee Chairman Devin Nu...,News,"December 31, 2017",0
2,Sheriff David Clarke Becomes An Internet Joke...,"On Friday, it was revealed that former Milwauk...",News,"December 30, 2017",0
3,Trump Is So Obsessed He Even Has Obama’s Name...,"On Christmas day, Donald Trump announced that ...",News,"December 29, 2017",0
4,Pope Francis Just Called Out Donald Trump Dur...,Pope Francis used his annual Christmas Day mes...,News,"December 25, 2017",0
...,...,...,...,...,...
21412,'Fully committed' NATO backs new U.S. approach...,BRUSSELS (Reuters) - NATO allies on Tuesday we...,worldnews,"August 22, 2017",1
21413,LexisNexis withdrew two products from Chinese ...,"LONDON (Reuters) - LexisNexis, a provider of l...",worldnews,"August 22, 2017",1
21414,Minsk cultural hub becomes haven from authorities,MINSK (Reuters) - In the shadow of disused Sov...,worldnews,"August 22, 2017",1
21415,Vatican upbeat on possibility of Pope Francis ...,MOSCOW (Reuters) - Vatican Secretary of State ...,worldnews,"August 22, 2017",1
21416,Indonesia to buy $1.14 billion worth of Russia...,JAKARTA (Reuters) - Indonesia will buy 11 Sukh...,worldnews,"August 22, 2017",1

In [13]:
news.isnull().sum()

title      0
text       0
subject    0
date       0
label      0
dtype: int64

In [14]:
columns_to_drop = ['title', 'subject', 'date']
existing_columns = [col for col in columns_to_drop if col in news.columns]
if existing_columns:
    news = news.drop(existing_columns, axis=1)

In [15]:
news

                                                    text  label
0      Donald Trump just couldn t wish all Americans ...      0
1      House Intelligence Committee Chairman Devin Nu...      0
2      On Friday, it was revealed that former Milwauk...      0
3      On Christmas day, Donald Trump announced that ...      0
4      Pope Francis used his annual Christmas Day mes...      0
...                                                  ...    ...
21412  BRUSSELS (Reuters) - NATO allies on Tuesday we...      1
21413  LONDON (Reuters) - LexisNexis, a provider of l...      1
21414  MINSK (Reuters) - In the shadow of disused Sov...      1
21415  MOSCOW (Reuters) - Vatican Secretary of State ...      1
21416  JAKARTA (Reuters) - Indonesia will buy 11 Sukh...      1

[44898 rows x 2 columns]

In [16]:
# news=news.drop(['index'],axis=1,inplace=True) # This line caused a KeyError because the 'index' column does not exist.

In [17]:
news

                                                    text  label
0      Donald Trump just couldn t wish all Americans ...      0
1      House Intelligence Committee Chairman Devin Nu...      0
2      On Friday, it was revealed that former Milwauk...      0
3      On Christmas day, Donald Trump announced that ...      0
4      Pope Francis used his annual Christmas Day mes...      0
...                                                  ...    ...
21412  BRUSSELS (Reuters) - NATO allies on Tuesday we...      1
21413  LONDON (Reuters) - LexisNexis, a provider of l...      1
21414  MINSK (Reuters) - In the shadow of disused Sov...      1
21415  MOSCOW (Reuters) - Vatican Secretary of State ...      1
21416  JAKARTA (Reuters) - Indonesia will buy 11 Sukh...      1

[44898 rows x 2 columns]

In [18]:
news = news.sample(frac=1).reset_index(drop=True)

In [19]:
news

                                                    text  label
0      The most infamous characters from Donald Trump...      0
1      Nancy Sinatra sent out an absolutely vile twee...      0
2      JACKSON, Miss. (Reuters) - U.S. President Dona...      1
3      President Obama made what was billed as an eco...      0
4      Donald Trump is doing exactly the opposite of ...      0
...                                                  ...    ...
44893  UNITED NATIONS/YANGON (Reuters) - U.S. Secreta...      1
44894  Ivanka Trump has been sort of the female face ...      0
44895  The enthusiasm for Hillary is well underwhelmi...      0
44896  LONDON (Reuters) - Britain should leave open t...      1
44897   LONG SHADOW: The wake of the recent mass trag...      0

[44898 rows x 2 columns]

In [20]:
news.head()

                                                text  label
0  The most infamous characters from Donald Trump...      0
1  Nancy Sinatra sent out an absolutely vile twee...      0
2  JACKSON, Miss. (Reuters) - U.S. President Dona...      1
3  President Obama made what was billed as an eco...      0
4  Donald Trump is doing exactly the opposite of ...      0

In [21]:
import re

In [22]:
def wordopt(text):
  text = text.lower()
  # Remove URLs
  text = re.sub(r'https?://\S+|www\.\S+', '', text)
  # Remove HTML tags
  text = re.sub(r'<.*?>', '', text)
  # Remove digits
  text = re.sub(r'\d', '', text)
  # Remove punctuation and special characters, but keep spaces
  text = re.sub(r'[^a-zA-Z\s]', ' ', text)
  # Remove newlines
  text = re.sub(r'\n', ' ', text)
  # Remove extra spaces
  text = re.sub(r'\s+', ' ', text).strip()
  return text

In [23]:
news['text']=news['text'].apply(wordopt)

In [24]:
news['text']=news['text'].apply(wordopt)

In [25]:
news['text']

0        the most infamous characters from donald trump...
1        nancy sinatra sent out an absolutely vile twee...
2        jackson miss reuters u s president donald trum...
3        president obama made what was billed as an eco...
4        donald trump is doing exactly the opposite of ...
                               ...
44893    united nations yangon reuters u s secretary of...
44894    ivanka trump has been sort of the female face ...
44895    the enthusiasm for hillary is well underwhelmi...
44896    london reuters britain should leave open the o...
44897    long shadow the wake of the recent mass traged...
Name: text, Length: 44898, dtype: object

In [26]:
x=news['text']
y=news['label']
x

0        the most infamous characters from donald trump...
1        nancy sinatra sent out an absolutely vile twee...
2        jackson miss reuters u s president donald trum...
3        president obama made what was billed as an eco...
4        donald trump is doing exactly the opposite of ...
                               ...
44893    united nations yangon reuters u s secretary of...
44894    ivanka trump has been sort of the female face ...
44895    the enthusiasm for hillary is well underwhelmi...
44896    london reuters britain should leave open the o...
44897    long shadow the wake of the recent mass traged...
Name: text, Length: 44898, dtype: object

In [27]:
y

0        0
1        0
2        1
3        0
4        0
        ..
44893    1
44894    0
44895    0
44896    1
44897    0
Name: label, Length: 44898, dtype: int64

In [28]:
from sklearn.model_selection import train_test_split

In [29]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.3)

In [30]:
x_train.shape

(31428,)

In [31]:
y_train.shape

(31428,)

In [32]:
from sklearn.feature_extraction.text import TfidfVectorizer
vectorization=TfidfVectorizer()
xv_train=vectorization.fit_transform(x_train)
xv_test=vectorization.transform(x_test)

In [33]:
xv_train

<Compressed Sparse Row sparse matrix of dtype 'float64'
	with 6466826 stored elements and shape (31428, 96407)>

In [34]:
xv_test

<Compressed Sparse Row sparse matrix of dtype 'float64'
	with 2732820 stored elements and shape (13470, 96407)>

In [35]:
from sklearn.linear_model import LogisticRegression

In [36]:
reg=LogisticRegression()
reg.fit(xv_train,y_train)

LogisticRegression()

In [37]:
predict=reg.predict(xv_test)

In [38]:
predict

array([1, 0, 0, ..., 1, 1, 1])

In [39]:
reg.score(xv_test,y_test)

0.9878990348923534

In [40]:
from sklearn.metrics import classification_report
print(classification_report(y_test,predict))

              precision    recall  f1-score   support

           0       0.99      0.99      0.99      6974
           1       0.98      0.99      0.99      6496

    accuracy                           0.99     13470
   macro avg       0.99      0.99      0.99     13470
weighted avg       0.99      0.99      0.99     13470

In [41]:
from sklearn.tree import DecisionTreeClassifier
dt=DecisionTreeClassifier()
dt.fit(xv_train,y_train)

DecisionTreeClassifier()

In [42]:
pred_dct=dt.predict(xv_test)
pred_dct

array([1, 0, 0, ..., 0, 1, 1])

In [43]:
dt.score(xv_test,y_test)

0.9956198960653304

In [44]:
print(classification_report(y_test,pred_dct))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00      6974
           1       1.00      1.00      1.00      6496

    accuracy                           1.00     13470
   macro avg       1.00      1.00      1.00     13470
weighted avg       1.00      1.00      1.00     13470

In [45]:
from sklearn.ensemble import RandomForestClassifier
rfc=RandomForestClassifier()
rfc.fit(xv_train,y_train)

RandomForestClassifier()

In [46]:
pred_rfc=rfc.predict(xv_test)
pred_rfc

array([1, 0, 0, ..., 1, 1, 1])

In [47]:
rfc.score(xv_test,y_test)

0.9904231625835189

In [48]:
print(classification_report(y_test,pred_rfc))

              precision    recall  f1-score   support

           0       0.99      0.99      0.99      6974
           1       0.99      0.99      0.99      6496

    accuracy                           0.99     13470
   macro avg       0.99      0.99      0.99     13470
weighted avg       0.99      0.99      0.99     13470

In [49]:
from sklearn.ensemble import GradientBoostingClassifier
gbc=GradientBoostingClassifier()
gbc.fit(xv_train,y_train)

GradientBoostingClassifier()

In [50]:
pred_gbc=gbc.predict(xv_test)
pred_gbc

array([1, 0, 0, ..., 0, 1, 1])

In [51]:
gbc.score(xv_test,y_test)

0.9959910913140312

In [52]:
print(classification_report(y_test,pred_gbc))

              precision    recall  f1-score   support

           0       1.00      0.99      1.00      6974
           1       0.99      1.00      1.00      6496

    accuracy                           1.00     13470
   macro avg       1.00      1.00      1.00     13470
weighted avg       1.00      1.00      1.00     13470

In [53]:
def ouput_label(n):
  if n==0:
    return "It is a fake news"
  elif n==1:
    return "It is a genuine news"

In [54]:
def manual_testing(news):
  testing_news={"text":[news]}
  new_def_test=pd.DataFrame(testing_news)
  new_def_test["text"]=new_def_test["text"].apply(wordopt)
  new_x_test=new_def_test["text"]
  new_xv_test=vectorization.transform(new_x_test)
  predict=reg.predict(new_xv_test)
  pred_rfc=rfc.predict(new_xv_test)
  pred_dct=dt.predict(new_xv_test)
  pred_gbc=gbc.predict(new_xv_test)
  print("\n\nLogistic Regression Prediction: {} ".format(ouput_label(predict[0])))
  print("\n\nRandom Forest Prediction:{}".format(ouput_label(pred_rfc[0])))
  print("\n\nDecision Tree Prediction:{}".format(output_label(pred_dct[0])))
  print("\n\nGradient Boosting Prediction:{}".format(output_label(pred_gbc[0])))

In [55]:
import pickle

# Save trained model
pickle.dump(reg, open("model.pkl", "wb"))

# Save TF-IDF vectorizer
pickle.dump(vectorization, open("vectorizer.pkl", "wb"))

In [59]:
from sklearn.ensemble import GradientBoostingClassifier

gbc = GradientBoostingClassifier(
    n_estimators=100,   # keep 50–100
    max_depth=3
)

gbc.fit(xv_train, y_train)

GradientBoostingClassifier()

In [60]:
pred_gbc=gbc.predict(xv_test)
pred_gbc

array([1, 0, 0, ..., 0, 1, 1])

In [61]:
gbc.score(xv_test,y_test)

0.9960653303637713

In [63]:
from google.colab import files

files.download("model.pkl")
files.download("vectorizer.pkl")